<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductInternalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [];

        for ($i = 1; $i <= 100; $i++) {
            $isDigital = $i <= 50;

            $productType = $isDigital ? 'digital' : 'physical';
            $status = collect(['in_stock', 'out_of_stock'])->random();
            $imagePath = $isDigital ? 'products/digital.png' : 'products/physical.png';

            $products[] = [
                'sku' => strtoupper(Str::random(8)),
                'internal_code' => 'INT-' . rand(10000, 99999),
                'batch_number' => $isDigital ? null : 'BATCH-' . rand(1000, 9999),
                'location' => $isDigital ? null : 'Warehouse ' . rand(1, 3),
                'stock_quantity' => $isDigital ? 0 : rand(0, 100),
                'min_stock_threshold' => $isDigital ? null : rand(1, 10),
                'max_stock_threshold' => $isDigital ? null : rand(50, 200),
                'unit' => $isDigital ? null : 'pcs',
                'price' => rand(1000, 9999) / 100,
                'wholesale_price' => rand(800, 950) / 100,
                'retail_price' => rand(1000, 1200) / 100,
                'product_type' => $productType,
                'file_path' => $isDigital ? 'files/product_' . $i . '.zip' : null,
                'download_url' => $isDigital ? 'https://example.com/downloads/product_' . $i : null,
                'license_key' => $isDigital ? Str::upper(Str::random(16)) : null,
                'max_downloads' => $isDigital ? rand(1, 10) : null,
                'access_expires_at' => $isDigital ? Carbon::now()->addDays(rand(7, 30)) : null,
                'is_active' => true,
                'is_discontinued' => false,
                'status' => $status,
                'received_at' => !$isDigital ? Carbon::now()->subDays(rand(0, 60)) : null,
                'expires_at' => !$isDigital ? Carbon::now()->addMonths(rand(1, 12)) : null,
                'notes' => 'Generated by seeder.',
                'attributes' => json_encode([
                    'color' => collect(['red', 'blue', 'green', 'black'])->random(),
                    'size' => collect(['S', 'M', 'L', 'XL'])->random(),
                ]),
                'image_path' => $imagePath,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('product_internals')->insert($products);
    }
}
